name: CI/CD Build & Deploy (Minikube Runner)

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/wisecow:latest

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube version

      - name: Setup Minikube kubeconfig
        run: |
          mkdir -p $HOME/.kube
          minikube start --driver=docker
          minikube update-context
          chmod 600 $HOME/.kube/config

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Update k8s manifests image
        run: |
          yq -i '.spec.template.spec.containers[0].image = "docker.io/'"${{ secrets.DOCKERHUB_USERNAME }}"'/wisecow:latest"' k8s/deployment.yaml

      - name: Apply manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Get Pods
        run: kubectl get pods -n default
